### ISSUE TITLE
스레드 충돌로 인한 GUI 강제종료 현상

### ISSUE THREAD

**Issue by solifidian** [DCP-arca/NAI-Auto-Generator#1]
안녕하세요, NAI-Auto-Generator를 잘 사용중입니다.

지금까지의 업데이트로 인해 많은 버그가 잡혔으나, 아직 일부 상황에서 GUI가 강제 종료되는 현상이 있습니다.
직접 발생하는 부분과 원인으로 예상되는 것을 확인하여 참고를 위해 issue로 전달 드립니다.

현재 문제가 발생하는 것으로 확인된 부분은 gui.py의 line:413입니다.
해당 위치의 코드는 아래와 같습니다.
self.dict_ui_settings["seed"].setText(str(data["seed"]))

AutoGenerateThread 내에서 생성된 시드값을 GUI에 반영하기 위해, Main Thread의 GUI에 Access 하는 과정에서 충돌이 발생하는 것으로 보입니다.
스레드 충돌 문제라서 try except를 써도 아무런 에러가 잡히지 않고 GUI가 강제로 다운됩니다.

아래 문서를 보면 위와 같이 다른 Thread에서 직접 pyqt5의 Main Thread에 접근하는 것은 위험하다고 합니다.
https://github.com/qgis/QGIS/issues/50774

잠재적인 문제 해결을 위해서는, AutoGenerateThread에서 Statusbar에 접근 할 때와 같은 방식으로, 위의 해당된 부분을 포함한 GUI 접근 부분을 Signal을 사용해 접근하도록 업데이트 해야할 것 같습니다.

해당 문제를 재현하는 정확한 절차를 전달드리지 못해 죄송합니다. 문제 발생이 상당히 비규칙적입니다.

현재까지 확인한 바로는, NAI-Auto-Generator의 Auto Generate만 작동하고 아무런 작업을 하고 있지 않을 때에는 이 문제는  발생하지 않습니다.
NAI-Auto-Generator의 Auto Generate가 작동중인 상황에서 CPU Thread를 많이 사용하는 다른 작업(그러니까 고사양 게임 같은 것들)을 하고 있으면 발생하는 것으로 보입니다.

**Comment by DCP-arca** [comment]
이슈 써주셔서 고맙습니다
요즘 시간이 없어서 코드 읽을 겨를이 없다보니 날림으로 코드처리하는게 많네요;;
이전에 쓰레드 안쓸때의 코드가 아직도 남아있었나봅니다
시간나면 고쳐서 올려보겠습니다

**Comment by solifidian** [comment]
빠른 확인 감사합니다!
